// MIDI output — Tauri-only (midir-backed Rust bridge). The app is native-only;
// the old Web MIDI (navigator.requestMIDIAccess) backend was removed 2026-07-06.

import { engineTimeToPerfMs } from './engineClock';
import { invoke } from '@tauri-apps/api/core';

export interface MIDIOutputInfo {
  id: string;
  name: string;
}

// 'unsupported' / 'denied' were the Web MIDI backend's states; the native
// bridge never produces them, but MidiBar still branches on the full union.
type Status = 'unsupported' | 'idle' | 'requesting' | 'ready' | 'denied';

let outputs: MIDIOutputInfo[] = [];
let status: Status = 'idle';
const listeners = new Set<() => void>();

interface MidiPorts {
  inputs: string[];
  outputs: string[];
}

let tauriPoll: number | null = null;

async function refreshTauriOutputs(): Promise<void> {
  try {
    const ports = await invoke<MidiPorts>('midi_list_ports');
    // Port name doubles as id in Tauri mode — names are stable across replug.
    const next: MIDIOutputInfo[] = ports.outputs.map((n) => ({ id: n, name: n }));
    const changed =
      next.length !== outputs.length ||
      next.some((o, i) => o.id !== outputs[i]?.id);
    if (changed) {
      outputs = next;
      for (const cb of listeners) cb();
    }
  } catch (err) {
    console.warn('[midiOut] refresh failed:', err);
  }
}

export async function initMIDIOut(): Promise<boolean> {
  if (status === 'ready') return true;
  status = 'requesting';
  await refreshTauriOutputs();
  status = 'ready';
  if (tauriPoll === null) {
    // Hot-plug discovery — midir has no event stream so we poll. 3 s is
    // unobtrusive and replug is rare during a session.
    tauriPoll = window.setInterval(() => {
      void refreshTauriOutputs();
    }, 3000);
  }
  return true;
}

export function midiOutStatus(): Status {
  return status;
}

export function getMIDIOutputs(): MIDIOutputInfo[] {
  return outputs;
}

export function onMIDIOutputsChanged(cb: () => void): () => void {
  listeners.add(cb);
  return () => {
    listeners.delete(cb);
  };
}

const NOTE_ON = 0x90;
const NOTE_OFF = 0x80;
const CONTROL_CHANGE = 0xb0;
const PROGRAM_CHANGE = 0xc0;
// System realtime messages — single byte, no channel, broadcast on the whole
// port. Clock pulses (0xF8) are generated by the native clock thread, not
// here — JS sends only the transport brackets.
const MIDI_START = 0xfa;
const MIDI_STOP = 0xfc;
const CC_BANK_MSB = 0;
const CC_BANK_LSB = 32;

// Scheduler `when` values are engine-clock seconds; convert through the
// engine-clock extrapolator so MIDI sends line up with the audio voices
// targeting the same instant.
function audioToPerfMs(audioTime: number): number {
  return engineTimeToPerfMs(audioTime);
}

function tauriSend(portName: string, bytes: number[]) {
  invoke('midi_send', { portName, bytes }).catch((err) => {
    console.warn(`[midiOut] send to ${portName} failed:`, err);
  });
}

// Pending note-on/off timers, so a transport stop / panic can cancel sends
// scheduled behind the 250ms horizon (otherwise they fire AFTER the
// all-notes-off and leave ghost notes ringing on external hardware). Clock
// pulses deliberately don't register here — the clock-out stream is
// free-running and must survive stops.
const pendingNoteTimers = new Set<number>();

function scheduleTauri(
  portName: string,
  bytes: number[],
  whenPerfMs: number,
  cancelable = false
) {
  const delay = Math.max(0, whenPerfMs - performance.now());
  if (delay <= 0) {
    tauriSend(portName, bytes);
  } else if (cancelable) {
    const id = window.setTimeout(() => {
      pendingNoteTimers.delete(id);
      tauriSend(portName, bytes);
    }, delay);
    pendingNoteTimers.add(id);
  } else {
    window.setTimeout(() => tauriSend(portName, bytes), delay);
  }
}

// Cancel every scheduled (not-yet-sent) note-on/off. Called from the transport
// stop path and midiPanic — the panic's all-notes-off only silences notes that
// already STARTED; this stops the queued ones from starting at all.
export function cancelScheduledMidi(): void {
  for (const id of pendingNoteTimers) window.clearTimeout(id);
  pendingNoteTimers.clear();
}

export function sendMIDINote(
  deviceId: string,
  channel: number,
  note: number,
  velocity: number,
  when: number,
  durationS: number
) {
  const ch = ((channel | 0) & 0x0f);
  const n = Math.max(0, Math.min(127, note | 0));
  const v = Math.max(1, Math.min(127, Math.round(velocity * 127)));
  const onMs = audioToPerfMs(when);
  const offMs = audioToPerfMs(when + Math.max(0.02, durationS));
  scheduleTauri(deviceId, [NOTE_ON | ch, n, v], onMs, true);
  scheduleTauri(deviceId, [NOTE_OFF | ch, n, 0], offMs, true);
}

// Immediate note-on / note-off pair for LIVE play (keyboard monitor). Unlike
// sendMIDINote, the off isn't scheduled — duration is unknown at press time, so
// the caller sends the off when the key is released. Sent now (no audio-clock
// scheduling): live play wants the lowest latency, not sample-accurate timing.
export function sendMIDINoteOn(
  deviceId: string,
  channel: number,
  note: number,
  velocity: number
) {
  const ch = (channel | 0) & 0x0f;
  const n = Math.max(0, Math.min(127, note | 0));
  const v = Math.max(1, Math.min(127, Math.round(velocity * 127)));
  tauriSend(deviceId, [NOTE_ON | ch, n, v]);
}

export function sendMIDINoteOff(deviceId: string, channel: number, note: number) {
  const ch = (channel | 0) & 0x0f;
  const n = Math.max(0, Math.min(127, note | 0));
  tauriSend(deviceId, [NOTE_OFF | ch, n, 0]);
}

export function sendMIDIProgram(deviceId: string, channel: number, program: number) {
  const ch = ((channel | 0) & 0x0f);
  const p = Math.max(0, Math.min(127, program | 0));
  tauriSend(deviceId, [PROGRAM_CHANGE | ch, p]);
}

// Send a Control Change immediately (no scheduling — these are knob-driven
// param updates, not note-timed events). value is the raw 0..127 CC value.
export function sendMIDIControlChange(
  deviceId: string,
  channel: number,
  cc: number,
  value: number
) {
  const ch = (channel | 0) & 0x0f;
  const n = Math.max(0, Math.min(127, cc | 0));
  const v = Math.max(0, Math.min(127, value | 0));
  tauriSend(deviceId, [CONTROL_CHANGE | ch, n, v]);
}

export function sendPatchSelect(
  deviceId: string,
  channel: number,
  bankMSB: number | null,
  bankLSB: number | null,
  program: number | null
) {
  const ch = ((channel | 0) & 0x0f);
  if (bankMSB !== null) {
    tauriSend(deviceId, [CONTROL_CHANGE | ch, CC_BANK_MSB, Math.max(0, Math.min(127, bankMSB | 0))]);
  }
  if (bankLSB !== null) {
    tauriSend(deviceId, [CONTROL_CHANGE | ch, CC_BANK_LSB, Math.max(0, Math.min(127, bankLSB | 0))]);
  }
  if (program !== null) {
    tauriSend(deviceId, [PROGRAM_CHANGE | ch, Math.max(0, Math.min(127, program | 0))]);
  }
}

export function resolveDeviceId(portName: string | null, fallbackId: string | null): string | null {
  if (portName) {
    const needle = portName.toLowerCase();
    const match = outputs.find((o) => o.name.toLowerCase().includes(needle));
    if (match) return match.id;
  }
  return fallbackId;
}

export function midiPanic() {
  // Drop queued note sends first so nothing re-triggers after the panic.
  cancelScheduledMidi();
  invoke('midi_panic').catch((err) => console.warn('[midiOut] panic failed:', err));
}

// Transport realtime messages, sent immediately (no scheduling) — they bracket
// the pulse stream on the play/stop action. Start resets followers to bar 1.

export function sendMIDIStart(deviceId: string) {
  tauriSend(deviceId, [MIDI_START]);
}

export function sendMIDIStop(deviceId: string) {
  tauriSend(deviceId, [MIDI_STOP]);
}

// HMR cleanup — without this, the Tauri hot-plug polling setInterval gets
// orphaned on module reload and a new one stacks on next init.
if (import.meta.hot) {
  import.meta.hot.dispose(() => {
    if (tauriPoll !== null) {
      window.clearInterval(tauriPoll);
      tauriPoll = null;
    }
    cancelScheduledMidi();
  });
}
