// Native reverb — Faust-compiled Griesinger plate (Clouds-flavoured),
// same .dsp source as the existing Web Audio worklet and the GlitchFX
// VST. The Rust code in `reverb_dsp.rs` is generated by Faust's Rust
// backend and committed as-is; regenerate after editing the .dsp with:
//
//   faust -lang rust ../vst/glitch/dsp/reverb.dsp \
//     -o sequencer/src-tauri/src/reverb_dsp.rs
//
// This module provides the scaffolding the generated code expects
// (FaustFloat, ParamIndex, UI/Meta traits) and a clean `ReverbBus`
// wrapper used by audio.rs. The wet/dry split inside the .dsp is
// pinned to fully-wet on init — our native architecture mixes dry +
// wet at the per-voice fxSend level, not inside the reverb DSP, so
// the UI's "mix" parameter is reinterpreted on the Rust side as a
// global wet-bus gain (see audio.rs).

#![allow(unused_parens)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(dead_code)]
#![allow(unused_variables)]
#![allow(unused_mut)]
#![allow(non_upper_case_globals)]
#![allow(clippy::all)]

// --- Faust runtime scaffolding ----------------------------------------------

#[allow(dead_code)]
type F32 = f32;
#[allow(dead_code)]
type F64 = f64;
type FaustFloat = F32;

#[derive(Copy, Clone)]
pub struct ParamIndex(pub i32);

pub trait Meta {
  fn declare(&mut self, key: &str, value: &str);
}

pub trait UI<T> {
  fn open_tab_box(&mut self, label: &str);
  fn open_horizontal_box(&mut self, label: &str);
  fn open_vertical_box(&mut self, label: &str);
  fn close_box(&mut self);
  fn add_button(&mut self, label: &str, param: ParamIndex);
  fn add_check_button(&mut self, label: &str, param: ParamIndex);
  fn add_vertical_slider(
    &mut self,
    label: &str,
    param: ParamIndex,
    init: T,
    min: T,
    max: T,
    step: T,
  );
  fn add_horizontal_slider(
    &mut self,
    label: &str,
    param: ParamIndex,
    init: T,
    min: T,
    max: T,
    step: T,
  );
  fn add_num_entry(
    &mut self,
    label: &str,
    param: ParamIndex,
    init: T,
    min: T,
    max: T,
    step: T,
  );
  fn add_horizontal_bargraph(&mut self, label: &str, param: ParamIndex, min: T, max: T);
  fn add_vertical_bargraph(&mut self, label: &str, param: ParamIndex, min: T, max: T);
  fn declare(&mut self, param: Option<ParamIndex>, key: &str, value: &str);
}

// Generated reverb code expects this trait to be in scope on `mydsp`.
pub trait FaustDsp {
  type T;
  fn new() -> Self
  where
    Self: Sized;
  fn metadata(&self, m: &mut dyn Meta);
  fn get_sample_rate(&self) -> i32;
  fn get_num_inputs(&self) -> i32;
  fn get_num_outputs(&self) -> i32;
  fn class_init(sample_rate: i32)
  where
    Self: Sized;
  fn instance_reset_params(&mut self);
  fn instance_clear(&mut self);
  fn instance_constants(&mut self, sample_rate: i32);
  fn instance_init(&mut self, sample_rate: i32);
  fn init(&mut self, sample_rate: i32);
  fn build_user_interface(&self, ui_interface: &mut dyn UI<Self::T>);
  fn build_user_interface_static(ui_interface: &mut dyn UI<Self::T>)
  where
    Self: Sized;
  fn get_param(&self, param: ParamIndex) -> Option<Self::T>;
  fn set_param(&mut self, param: ParamIndex, value: Self::T);
  fn compute(
    &mut self,
    count: i32,
    inputs: &[&[Self::T]],
    outputs: &mut [&mut [Self::T]],
  );
}

// --- Generated DSP (Faust output) -------------------------------------------
//
// The `super::*` bring the scaffolding above (FaustFloat, ParamIndex,
// UI, Meta, FaustDsp) into scope so the generated impls compile.

mod dsp {
  use super::*;
  include!("reverb_dsp.rs");
}

// --- Public wrapper ---------------------------------------------------------
//
// Param indices come from the generated build_user_interface_static —
// damping=0, diffusion=1, mix=2, size=3.
const PARAM_DAMPING: ParamIndex = ParamIndex(0);
const PARAM_DIFFUSION: ParamIndex = ParamIndex(1);
const PARAM_MIX: ParamIndex = ParamIndex(2);
const PARAM_SIZE: ParamIndex = ParamIndex(3);

pub struct ReverbBus {
  inner: dsp::mydsp,
}

impl ReverbBus {
  pub fn new(sample_rate: u32) -> Self {
dsp::mydsp::class_init(sample_rate as i32);
    let mut inner = dsp::mydsp::new();
    inner.init(sample_rate as i32);
    Self { inner }
  }

  pub fn set_size(&mut self, v: f32) {
self.inner.set_param(PARAM_SIZE, v.clamp(0.0, 1.0));
  }
  pub fn set_diffusion(&mut self, v: f32) {
self.inner.set_param(PARAM_DIFFUSION, v.clamp(0.0, 0.85));
  }
  pub fn set_damping(&mut self, v: f32) {
self.inner.set_param(PARAM_DAMPING, v.clamp(0.0, 1.0));
  }
  // Reverb internal wet/dry crossfade — controls how much of the dry
  // input bleeds through alongside the tank's wet tail. At mix=0 the
  // reverb passes the (already saturated) input straight through;
  // at mix=1 it's fully wet tail only. The "drive" stage upstream
  // stays audible at any mix because mix=0 just means "no reverb
  // tail," not "no FX bus output."
  pub fn set_mix(&mut self, v: f32) {
self.inner.set_param(PARAM_MIX, v.clamp(0.0, 1.0));
  }

  // Panic: zero the tank's internal state (delay lines / filter memory) so a
  // ringing or self-oscillating tail is silenced instantly. Params are kept —
  // only the audio memory is cleared. Called on the audio thread.
  pub fn clear(&mut self) {
    self.inner.instance_clear();
  }

  // Compute one block in-place: writes wet output to (out_l, out_r).
  // Inputs and outputs must be the same length. Slices must be non-zero
  // — Faust panics on empty input/output buffers.
  pub fn process_block(
    &mut self,
    in_l: &[f32],
    in_r: &[f32],
    out_l: &mut [f32],
    out_r: &mut [f32],
  ) {
let count = in_l
      .len()
      .min(in_r.len())
      .min(out_l.len())
      .min(out_r.len());
    if count == 0 {
      return;
    }
    let inputs: [&[f32]; 2] = [&in_l[..count], &in_r[..count]];
    // Faust's compute signature is &mut [&mut [f32]] — build the outer
    // mutable slice from individually-borrowed channel slices.
    let (out_l, out_r) = (&mut out_l[..count], &mut out_r[..count]);
    let mut outputs: [&mut [f32]; 2] = [out_l, out_r];
    self.inner.compute(count, &inputs, &mut outputs);
  }
}
