// Convert 128x64 images into Launch Control XL3 display payloads.
//
// The XL3 screen is 128x64, 1bpp. Pixels are packed 7-per-byte (MIDI-safe:
// every data byte stays 0..127) → ceil(128/7) = 19 bytes per row × 64 rows =
// 1216 bytes, matching Novation's documented display size.
//
// Usage (from the sequencer/ dir):
//   node scripts/xl3-bitmap.mjs MIXER=/abs/path/mixer.jpg SEQUENCE=/abs/path/sequence.jpg
// Writes src/midi/xl3Bitmaps.ts. Re-run after changing the source images.
//
// Three tunables are confirmed on-device once we can actually push a frame
// (the packing bit-order / polarity isn't fully specified in public docs):
//   INVERT     — flip if the panel renders dark-on-light
//   THRESHOLD  — gray cutoff for on/off
//   MSB_FIRST  — leftmost pixel = bit6 of the 7 (vs bit0)
//
// Requires ffmpeg on PATH (used purely to decode+downscale to raw grayscale).

import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const WIDTH = 128;
const HEIGHT = 64;
const BYTES_PER_ROW = 19;
const PX_PER_BYTE = 7;

const INVERT = false;
const THRESHOLD = 128;
const MSB_FIRST = true;

function toGray(path) {
  const dir = mkdtempSync(join(tmpdir(), 'xl3-'));
  const out = join(dir, 'g.gray');
  execFileSync(
    'ffmpeg',
    ['-y', '-i', path, '-vf', `scale=${WIDTH}:${HEIGHT}`, '-f', 'rawvideo', '-pix_fmt', 'gray', out],
    { stdio: 'ignore' }
  );
  const buf = readFileSync(out);
  if (buf.length !== WIDTH * HEIGHT) {
    throw new Error(`${path}: expected ${WIDTH * HEIGHT} gray bytes, got ${buf.length}`);
  }
  return buf;
}

function pack(gray) {
  const out = [];
  for (let y = 0; y < HEIGHT; y++) {
    for (let bx = 0; bx < BYTES_PER_ROW; bx++) {
      let byte = 0;
      for (let bit = 0; bit < PX_PER_BYTE; bit++) {
        const x = bx * PX_PER_BYTE + bit;
        let on = 0;
        if (x < WIDTH) {
          on = gray[y * WIDTH + x] >= THRESHOLD ? 1 : 0;
          if (INVERT) on ^= 1;
        }
        const pos = MSB_FIRST ? PX_PER_BYTE - 1 - bit : bit;
        byte |= on << pos;
      }
      out.push(byte & 0x7f);
    }
  }
  return out;
}

const args = process.argv.slice(2);
if (args.length === 0) {
  console.error('usage: node scripts/xl3-bitmap.mjs NAME=/abs/path.jpg [NAME2=/abs/path2.jpg ...]');
  process.exit(1);
}

const entries = args.map((arg) => {
  const eq = arg.indexOf('=');
  const name = arg.slice(0, eq);
  const path = arg.slice(eq + 1);
  return { name, bytes: pack(toGray(path)) };
});

let ts = '// AUTO-GENERATED by scripts/xl3-bitmap.mjs — do not edit by hand.\n';
ts += '// 128x64 1bpp Launch Control XL3 display payloads (1216 bytes, 7-bit packed).\n';
ts += '// Re-run the script after changing the source images.\n\n';
for (const e of entries) {
  ts += `export const ${e.name}_BITMAP: readonly number[] = [\n`;
  for (let i = 0; i < e.bytes.length; i += BYTES_PER_ROW) {
    ts += '  ' + e.bytes.slice(i, i + BYTES_PER_ROW).join(', ') + ',\n';
  }
  ts += '];\n\n';
}

const outFile = join(process.cwd(), 'src/midi/xl3Bitmaps.ts');
writeFileSync(outFile, ts);
console.log('wrote', outFile, '—', entries.map((e) => `${e.name}=${e.bytes.length}B`).join(' '));
